language: python

env:
  - TOXENV=django19
  - TOXENV=django110
  - TOXENV=django111
  - TOXENV=django2

install:
  - pip install tox
  - pip install coveralls

script:
  - tox
after_success:
  - coveralls
