language: python

matrix:
 include:
  - python: 2.7
    env:
      - TOXENV=django19
      - TOXENV=django110
      - TOXENV=django111
  - python: 3.5
    env: TOXENV=django2
  - python: 3.6
    env: TOXENV=django111

install:
  - pip install tox
  - pip install coveralls

script:
  - tox

after_success:
  - coveralls
